# Generated by Django 4.0.5 on 2022-07-01 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commission', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
